# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ release ]

# defaults:
#   run:
#     working-directory: /Users/patrick/dev/familydiagram

jobs:
  build-osx:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PATRICKKIDD_CI_TOKEN }}
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
        cache: 'pipenv'
        # cache-dependency-path: '**/Pipfile.lock'        
    - run: |
        pip install pipenv
        cd familydiagram && pipenv install

    # Wasn't working for some reason
    # - name: Cache Qt@5
    #   id: cache-qt
    #   uses: actions/cache@v2
    #   with:
    #     path: /usr/local/opt/qt@5
    #     key: qt-${{ runner.os }}-1 # increment to re-populate
    
    - name: brew install qt@5
      # if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        brew install qt@5
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH

    - name: Cache vedanaprivate & _pkdiagram
      id: cache-private-plugins
      uses: actions/cache@v2
      with:
        path: |
          familydiagram/pkdiagram/_pkdiagram/build
          familydiagram/vedanaprivate/build
        key: private-plugins-${{ runner.os }}-${{ hashFiles('./familydiagram/pkdiagram/_pkdiagram/sip/*.sip', './familydiagram/pkdiagram/_pkdiagram/*.h', './familydiagram/pkdiagram/_pkdiagram/*.cpp', './familydiagram/vedanaprivate/sip/*.sip', './familydiagram/vedanaprivate/*.h', './familydiagram/vedanaprivate/*.cpp') }}
    
    - name: sip-build for vedanaprivate & _pkdiagram
      if: steps.cache-private-plugins.outputs.cache-hit != 'true'
      env:
        SSH_KEY: ${{ secrets.turin_secret_key }}
      run: |
        # git submodule update --init vedanaprivate
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        cd familydiagram/vedanaprivate && pipenv run sip-build; cd ..
        cd familydiagram/pkdiagram/_pkdiagram && pipenv run sip-build
        
    - name: Cache sysroot
      id: cache-sysroot
      uses: actions/cache@v2
      with:
        path: ./familydiagram/sysroot/sysroot-macos-64
        key: sysroot-macOS-020dfd0a8e6a2c8cf19554a6ab0f76fee27d114c05f3ff406377875191ad6e82
        # key: sysroot-${{ runner.os }}-${{ hashFiles('./familydiagram/sysroot/sysroot.toml') }}
    
    - name: Build sysroot
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      run: |
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        wget -L "https://www.zlib.net/fossils/zlib-1.2.11.tar.gz" -P ./sysroot/
        which qmake
        pipenv run pyqtdeploy-sysroot --target macos-64 --verbose sysroot/sysroot.toml
  
    # # - name: Install Qt
    # #   uses: jurplel/install-qt-action@v2
    # #   with:
    # #     # version:      ${{ env.QT_VERSION }}
    # #     version:      5.15.2
    # #     host:         mac
    # #     target:       desktop
    # #     dir:          ${{ runner.temp }}
    # #     modules:      qtcore qtgui qtwidgets qtprintsupport qtnetwork qtmacextras qtqml qtquick qtquickwidgets
    # #     setup-python: false

    - name: Import certificates and profiles into keychain
      run: |
        # Encrypt files
        openssl aes-256-cbc -k ${{ secrets.ENCRYPTION_PASSWORD }} -in familydiagram/.github/secrets/Certificates.p12.enc -out familydiagram/.github/secrets/Certificates.p12 -d
        openssl aes-256-cbc -k ${{ secrets.ENCRYPTION_PASSWORD }} -in familydiagram/.github/secrets/Family_Diagram_Distribution_Developer_ID.provisionprofile.enc -out .github/secrets/Family_Diagram_Distribution_Developer_ID.provisionprofile -d

        KEYCHAIN=build.keychain
        KEYCHAIN_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}

        # Create keychain
        security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN
        security default-keychain -s $KEYCHAIN
        security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN
        security import familydiagram/.github/secrets/Certificates.p12 -k $KEYCHAIN -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN

    - name: Build app
      run: |
        cd familydiagram && pipenv run bin/build.sh osx-release

    # # - name: Upload Artifact
    # #   uses: actions/upload-artifact@v2
    # #   with:
    # #     name: familydiagram-macos
    # #     path: build/osx/Release/  # Replace with the actual path to your app's build artifacts
  